#Villagers
VILLAGER_LIFESPAN: 15 #days
#PvP
SHIELD_COOLDOWN: 3 #seconds
ARROW_DAMAGE_INCREASE: 1.25
HORSE_DAMAGE_REDUCTION: 0.7
GAPPLE_COOLDOWN_SECONDS: 10 #seconds
#XP
PIG_COW_SHEEP_XP: 2
CHICKENXP: 1
CROPXP: 1
#Mob Spawning
MOB_SPAWNING_TPS: 18